// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Count:       newCount(db, opts...),
		Device:      newDevice(db, opts...),
		Rssi:        newRssi(db, opts...),
		Temperature: newTemperature(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Count       count
	Device      device
	Rssi        rssi
	Temperature temperature
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Count:       q.Count.clone(db),
		Device:      q.Device.clone(db),
		Rssi:        q.Rssi.clone(db),
		Temperature: q.Temperature.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Count:       q.Count.replaceDB(db),
		Device:      q.Device.replaceDB(db),
		Rssi:        q.Rssi.replaceDB(db),
		Temperature: q.Temperature.replaceDB(db),
	}
}

type queryCtx struct {
	Count       *countDo
	Device      *deviceDo
	Rssi        *rssiDo
	Temperature *temperatureDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Count:       q.Count.WithContext(ctx),
		Device:      q.Device.WithContext(ctx),
		Rssi:        q.Rssi.WithContext(ctx),
		Temperature: q.Temperature.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
