// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCount = "count"

// Count mapped from table <count>
type Count struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DeviceID   int64     `gorm:"column:device_id;not null" json:"device_id"`
	RecordedAt time.Time `gorm:"column:recorded_at;primaryKey" json:"recorded_at"`
	Value      int32     `gorm:"column:value;not null" json:"value"`
}

// TableName Count's table name
func (*Count) TableName() string {
	return TableNameCount
}
