// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDevice = "device"

// Device mapped from table <device>
type Device struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Deviceid string `gorm:"column:deviceid;not null" json:"deviceid"`
	Label    string `gorm:"column:label" json:"label"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
