// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRssi = "rssi"

// Rssi mapped from table <rssi>
type Rssi struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DeviceID   int64     `gorm:"column:device_id;not null" json:"device_id"`
	RecordedAt time.Time `gorm:"column:recorded_at;primaryKey" json:"recorded_at"`
	Value      int32     `gorm:"column:value;not null" json:"value"`
}

// TableName Rssi's table name
func (*Rssi) TableName() string {
	return TableNameRssi
}
