// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemperature = "temperature"

// Temperature mapped from table <temperature>
type Temperature struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DeviceID   int64     `gorm:"column:device_id;not null" json:"device_id"`
	RecordedAt time.Time `gorm:"column:recorded_at;primaryKey" json:"recorded_at"`
	Value      float64   `gorm:"column:value;not null" json:"value"`
}

// TableName Temperature's table name
func (*Temperature) TableName() string {
	return TableNameTemperature
}
